replicaCount: 1

image:
  repository: quay.io/redhat-chaos/cerberus
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}

kubeconfigSecretName: cerberus-kubeconfig

cerberus:
  workdir: /tmp/cerberus
  outputPath: /tmp/cerberus/cerberus.report
  kubeconfig_path: /root/.kube/config
  distribution: openshift
  port: 8080
  watch_nodes: true
  watch_cluster_operators: true
  watch_url_routes: []
  watch_master_schedulable:
    enabled: true
    label: node-role.kubernetes.io/master
  watch_namespaces:
    - gitops
  cerberus_publish_status: true
  inspect_components: false
  prometheus_url: ""
  prometheus_bearer_token: ""
  slack_integration: false
  watcher_slack_ID:
    Monday: ""
    Tuesday: ""
    Wednesday: ""
    Thursday: ""
    Friday: ""
    Saturday: ""
    Sunday: ""
  slack_team_alias: ""
  custom_checks: []
  kube_api_request_chunk_size: 250
  daemon_mode: true
  cores_usage_percentage: 0.5

tunings:
  iterations: 5
  sleep_time: 60

database:
  database_path: /tmp/cerberus.db
  reuse_database: false
