apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cerberus
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cerberus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cerberus
subjects:
  - kind: ServiceAccount
    name: cerberus
    namespace: default